name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ gcc make python3

      - name: Compile all .cpp, .c and run .py files
        run: |
          # Compile all .cpp files
          find . -name '*.cpp' | while read cpp_file; do
            echo "Compiling $cpp_file"
            g++ -Wall -g -std=c++20 -o "${cpp_file%.cpp}" "$cpp_file"
          done
          # Compile all .c files
          find . -name '*.c' | while read c_file; do
            echo "Compiling $c_file"
            gcc -Wall -g -std=c11 -o "${c_file%.c}" "$c_file"
          done
          # Run all .py files
          find . -name '*.py' | while read py_file; do
            echo "Running $py_file"
            python3 "$py_file"
          done
